backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "artists"
    label: "Artists"
    folder: "_artists/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    filter:
      field: name
      value: rammstein
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Started at", name: "date", widget: "datetime"}
      - {label: "Closed at", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Rating (scale of 1-5)", name: "rating", widget: "number", min: 0, max: 5}
      - {label: "Body", name: "body", widget: "markdown"}